version: "2.2"
services:
  contabil_bd:
    restart: always
    image: postgres:9.6
    #deploy:
    #  replicas: 1
    #  update_config:
    #    parallelism: 1
    #    delay: 10s
    #  restart_policy:
    #    condition: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=srbarri31
      - POSTGRES_DB=contabil
    networks:
     - contabil_network
    ports:
      - '5432'

  contabil_app:
    build:
      context: .
    image: contabil_app:latest            
    depends_on:
      - contabil_bd
    #deploy:
    #  replicas: 2
    #  update_config:
    #    parallelism: 2
    #    delay: 10s
    #  placement:
    #    constraints: [node.role == manager]  
    #  restart_policy:
    #    condition: on-failure  
    networks:
      - contabil_network
    ports:
      - '8080'

networks:
  contabil_network: 
