version: "2.2"
services:
  contabil_bd:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=srbarri31
      - POSTGRES_DB=contabil
    networks:
     - contabil_network
    ports:
      - '5432'

  contabil_app:
    build:
      context: .
    image: contabil_app:latest            
    depends_on:
      - contabil_bd
    networks:
      - contabil_network
    ports:
      - '8080'

networks:
  contabil_network: 
